import React, { useState } from 'react';
import {
  FileText,
  Search,
  Printer,
  FileSpreadsheet,
  Calendar,
  Layers,
  TrendingUp,
  Activity,
  DollarSign,
  Users,
  Bed,
  Pill,
  Truck,
  ShieldCheck
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { db } from '../../lib/database';
import { Badge } from '../../components/ui/Badge';
import { exportToCSV } from '../../lib/exportService';
import { openPrintWindow } from '../../lib/printService';

export const EnterpriseReportsPage: React.FC = () => {
  const { user, activeHospital } = useAuth();
  const hospId = activeHospital?.id;
  const isSuper = user?.is_super_admin;

  const [reportType, setReportType] = useState('revenue');
  const [dateRange, setDateRange] = useState('month');

  // Load live data from database
  const patients = db.getPatients(hospId, isSuper);
  const appointments = db.getAppointments(hospId, isSuper);
  const beds = db.getBeds(hospId, isSuper);
  const invoices = db.getInvoices(hospId, isSuper);
  const medicines = db.getMedicines(hospId, isSuper);
  const labOrders = db.getLabOrders(hospId, isSuper);
  const triageRecords = db.getTriageRecords(hospId, isSuper);
  const insuranceClaims = db.getInsuranceClaims(hospId, isSuper);

  const totalRev = invoices.reduce((acc, i) => acc + i.paid_amount, 0);
  const totalBeds = beds.length;
  const occBeds = beds.filter(b => b.status === 'occupied').length;

  const handleExportCurrentReport = () => {
    switch (reportType) {
      case 'revenue':
        exportToCSV(invoices, 'Hospital_Revenue_Report');
        break;
      case 'opd':
        exportToCSV(appointments, 'OPD_Appointments_Report');
        break;
      case 'ipd':
        exportToCSV(beds, 'IPD_Bed_Occupancy_Report');
        break;
      case 'pharmacy':
        exportToCSV(medicines, 'Pharmacy_Sales_Stock_Report');
        break;
      case 'laboratory':
        exportToCSV(labOrders, 'Laboratory_Orders_Report');
        break;
      case 'triage':
        exportToCSV(triageRecords, 'Emergency_Triage_Report');
        break;
      case 'insurance':
        exportToCSV(insuranceClaims, 'TPA_Insurance_Settlement_Report');
        break;
      default:
        exportToCSV(invoices, 'Hospital_Report');
    }
  };

  const handlePrintCurrentReport = () => {
    const html = `
      <div style="margin-bottom: 20px;">
        <div style="text-align: center; border-bottom: 2px solid #0f2444; padding-bottom: 8px; margin-bottom: 15px;">
          <div style="font-size: 16px; font-weight: 800; color: #0f2444;">EXECUTIVE CLINICAL & FINANCIAL REPORT</div>
          <div style="font-size: 11px; color: #0284c7; font-weight: 600;">REPORT MODULE: ${reportType.toUpperCase()} • GENERATED ON ${new Date().toLocaleDateString()}</div>
        </div>

        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 20px; font-size: 12px;">
          <div style="background: #f8fafc; border: 1px solid #cbd5e1; padding: 10px; border-radius: 6px;">
            <div style="color: #64748b; font-size: 10px;">TOTAL REVENUE</div>
            <div style="font-size: 16px; font-weight: bold; color: #0f2444;">₹${totalRev.toLocaleString()}</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #cbd5e1; padding: 10px; border-radius: 6px;">
            <div style="color: #64748b; font-size: 10px;">TOTAL REGISTERED PATIENTS</div>
            <div style="font-size: 16px; font-weight: bold; color: #0f2444;">${patients.length} UHIDs</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #cbd5e1; padding: 10px; border-radius: 6px;">
            <div style="color: #64748b; font-size: 10px;">BED OCCUPANCY RATIO</div>
            <div style="font-size: 16px; font-weight: bold; color: #0f2444;">${totalBeds ? Math.round((occBeds / totalBeds) * 100) : 0}%</div>
          </div>
        </div>

        <div style="font-size: 11px; color: #334155;">
          This executive summary is generated by Corot Healthcare Cloud ERP. Data is real-time and reflects tenant isolation policies.
        </div>
      </div>
    `;

    openPrintWindow(`EXECUTIVE REPORT - ${reportType.toUpperCase()}`, html, activeHospital || undefined);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900/40 border border-white/5 rounded-3xl p-6 backdrop-blur-xl">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Badge variant="blue" size="sm">ENTERPRISE BI & TELEMETRY</Badge>
            <span className="text-xs text-slate-400 font-mono">18+ ADVANCED ANALYTICAL SUITES</span>
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Enterprise Clinical & Financial Reports</h1>
          <p className="text-xs text-slate-400 mt-1">
            Executive operational insights, financial ledgers, clinical mortality rates, bed utilization, and drug consumption.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleExportCurrentReport}
            className="flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-slate-900/60 border border-white/5 text-slate-300 hover:text-white text-xs font-semibold"
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-400" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={handlePrintCurrentReport}
            className="flex items-center gap-2 px-5 py-2.5 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-[0_0_20px_rgba(37,99,235,0.4)]"
          >
            <Printer className="w-4 h-4" />
            <span>Print Executive PDF</span>
          </button>
        </div>
      </div>

      {/* Report Selector Tabs */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2 bg-slate-900/40 p-2 rounded-3xl border border-white/5">
        {[
          { id: 'revenue', label: 'Financial Revenue', icon: DollarSign },
          { id: 'opd', label: 'OPD Consultations', icon: Users },
          { id: 'ipd', label: 'IPD & Bed Matrix', icon: Bed },
          { id: 'pharmacy', label: 'Pharmacy Sales', icon: Pill },
          { id: 'laboratory', label: 'Pathology Tests', icon: Activity },
          { id: 'triage', label: 'Emergency Triage', icon: TrendingUp },
          { id: 'insurance', label: 'TPA Claims Desk', icon: ShieldCheck }
        ].map(r => {
          const Icon = r.icon;
          const isActive = reportType === r.id;
          return (
            <button
              key={r.id}
              onClick={() => setReportType(r.id)}
              className={`flex items-center gap-2 p-3 rounded-2xl text-xs font-semibold transition-all ${
                isActive
                  ? 'bg-blue-600 text-white shadow-[0_0_15px_rgba(37,99,235,0.4)]'
                  : 'bg-transparent text-slate-400 hover:text-white hover:bg-white/[0.02]'
              }`}
            >
              <Icon className="w-4 h-4 shrink-0" />
              <span className="truncate">{r.label}</span>
            </button>
          );
        })}
      </div>

      {/* Active Report View Details */}
      <div className="bg-slate-900/40 border border-white/5 rounded-3xl p-6 backdrop-blur-md space-y-6">
        <div className="flex items-center justify-between">
          <h3 className="font-bold text-white uppercase text-sm tracking-wider font-mono">
            {reportType.toUpperCase()} DATA BREAKDOWN &amp; LEDGER
          </h3>
          <span className="text-xs text-slate-400 font-mono">
            Filtered for {activeHospital?.name || 'All Hospitals'}
          </span>
        </div>

        {reportType === 'revenue' && (
          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5">
                <div className="text-xs text-slate-400 font-mono">REALIZED REVENUE</div>
                <div className="text-2xl font-bold text-emerald-400 font-mono mt-1">₹{totalRev.toLocaleString()}</div>
              </div>
              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5">
                <div className="text-xs text-slate-400 font-mono">TOTAL TRANSACTIONS</div>
                <div className="text-2xl font-bold text-white font-mono mt-1">{invoices.length}</div>
              </div>
              <div className="p-4 rounded-2xl bg-slate-900/80 border border-white/5">
                <div className="text-xs text-slate-400 font-mono">AVERAGE TICKET SIZE</div>
                <div className="text-2xl font-bold text-blue-400 font-mono mt-1">
                  ₹{invoices.length ? Math.round(totalRev / invoices.length).toLocaleString() : 0}
                </div>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-white/5 text-slate-400 font-mono uppercase text-[11px]">
                    <th className="pb-3 px-3">Invoice No</th>
                    <th className="pb-3 px-3">Patient</th>
                    <th className="pb-3 px-3">Amount (₹)</th>
                    <th className="pb-3 px-3">Mode</th>
                    <th className="pb-3 px-3">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {invoices.map(i => (
                    <tr key={i.id} className="hover:bg-white/[0.02]">
                      <td className="py-3 px-3 font-mono text-white">{i.invoice_no}</td>
                      <td className="py-3 px-3 text-slate-300">{i.patient_name}</td>
                      <td className="py-3 px-3 font-mono font-bold text-emerald-400">₹{i.grand_total.toLocaleString()}</td>
                      <td className="py-3 px-3 uppercase font-mono text-slate-400">{i.payment_mode}</td>
                      <td className="py-3 px-3">
                        <Badge variant={i.status === 'paid' ? 'emerald' : 'amber'} size="sm">
                          {i.status.toUpperCase()}
                        </Badge>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {reportType !== 'revenue' && (
          <div className="py-12 text-center text-slate-400">
            <Layers className="w-10 h-10 text-blue-400 opacity-40 mx-auto mb-3" />
            <h4 className="font-bold text-white text-base">Analytical Report Dataset Loaded</h4>
            <p className="text-xs text-slate-500 mt-1 max-w-md mx-auto">
              Ready for executive export. Click <strong>Export CSV</strong> above to download the raw dataset or <strong>Print Executive PDF</strong> for printable format.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
